feat: add vault
criticalmassbr/ms-utils pull request #14
Opened 2023-03-15 21:01 UTC by andersonhese

[Utils :: Adicionar Vault](https://dialog-ci.monday.com/boards/2750468636/pulses/4150033739)

2023-03-15 21:07 UTC, VitAndrGuid approved these changes

2023-03-16 12:07 UTC, gustavo-b requested changes

2023-03-16 12:07 UTC, gustavo-b commented on vault.go
> +		log.Fatalf("unable to login to Vault: %v", err)
Acredito que o `ms-utils` não deveria chamar `log.Fatal`, e apenas retornar o erro, dessa forma cada serviço que utilizar vai decidir o que fazer em caso de exceção e fica menos obscuro os possíveis pontos de saída do sistema.

2023-03-16 12:07 UTC, gustavo-b commented on vault.go
> +)
Como cada serviço pode ter necessidade de keys diferente, acredito que elas tem que ser definidas no próprio serviço que está chamando essa lib, senão esse arquivo pode crescer e ficar com regras que são específicas de um serviço ou outro.

2023-03-16 12:07 UTC, gustavo-b commented on vault.go
> +}
Assim como as keys, no `ms-utils` poderia ficar somente a parte que conecta com o vault e retorna dados (`GetSecret`). Cada serviço define quais variáveis ela precisa e cria os métodos e structs apropriadas pra seu uso.

2023-03-16 12:07 UTC, gustavo-b commented on vault.go
> +func (s *vaultService) getSecret(key VaultSecretKey, clientSlug string) (string, error) {
Esse método pode ser público porque é o que esse serviço expõe de funcionalidade.

2023-03-16 12:07 UTC, gustavo-b commented on health_check.go
> +		log.Fatalf("unable to read Vault certificate: %v", err)
Faz sentido o sistema morrer se o health check falhar aqui? Os outros só retornam erro em caso de falha.

2023-03-16 12:29 UTC, luk3skyw4lker requested changes

2023-03-16 12:29 UTC, luk3skyw4lker commented on vault.go
> +		span.End()
Aqui tu tá iniciando várias spans e finalizando elas, acho que iniciar a span como primeira coisa da função e terminar ela como última coisa é o suficiente.

2023-03-16 15:16 UTC, closed without merging